<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pradnya-Nandrekar" failures="1" tests="3" name="ECommerce_TestCases.TestCase08" time="23.533" errors="0" timestamp="2024-11-30T18:57:48 IST" skipped="2">
  <testcase classname="ECommerce_TestCases.TestCase08" name="Sorting_Product_L_H" time="23.533">
    <failure message="Sort By- price Low-High Failed..: lists don&#039;t have the same size expected [69] but found [121]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Sort By- price Low-High Failed..: lists don't have the same size expected [69] but found [121]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:1089)
at ECommerce_TestCases.TestCase08.Sorting_Product_L_H(TestCase08.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Sorting_Product_L_H -->
  <system-out>
    <![CDATA[Test Started]]>
  </system-out>
  <testcase classname="ECommerce_TestCases.TestCase08" name="Sorting_Product_rating">
    <skipped/>
  </testcase> <!-- Sorting_Product_rating -->
  <system-out/>
  <testcase classname="ECommerce_TestCases.TestCase08" name="Sorting_Product_Hgh_low">
    <skipped/>
  </testcase> <!-- Sorting_Product_Hgh_low -->
  <system-out/>
</testsuite> <!-- ECommerce_TestCases.TestCase08 -->
